version: '3.8'
services:
  nest-server:
    build: .
    ports:
      - '8000:8000'
    environment:
      NODE_ENV: production
      DATABASE_URL: 'postgresql://nestdb_owner:npg_EmxM8RHBOw6a@ep-nameless-bird-a18qlch8-pooler.ap-southeast-1.aws.neon.tech/nestdb?sslmode=require'
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 60s
      retries: 3
      start_period: 60s
      timeout: 60s

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
